### ISSUE TITLE
correct first example

### ISSUE THREAD

**Issue by GrosSacASac** [tc39/proposal-seeded-random#7]
for(const [i,r] of enumerate(Math.seededPRNG({seed:0}))) {
  // do something with each value
  if(i >= limit) break;
}

enumerate is not defined

**Comment by bakkot** [comment]
I imagine you're intended to assume something like
```js
function* enumerate(it) {
  let i = 0;
  for (let r of it) {
    yield [i++, r];
  }
}
```

(Which isn't to say the example shouldn't be clarified, just explaining what it presumably means.)

**Comment by GrosSacASac** [comment]
thanks, I think the example should not use a function that only exists in Python by default. 

**Proposal**: What if Math.seededPRNG just returned a function instead of an iterator, it could then be more polymorphic with Math.random which is also just a function and not an iterator.

```
const seededRandom = Math.seededPRNG({seed:0});
const normalRandom = Math.random;
// ... use normalRandom() and seededRandom() interchangeably
```

**Comment by tabatkins** [comment]
You get that from the `.next()` function on the returned iterator.

**Comment by GrosSacASac** [comment]
`.next()` returns `{done, value}` instead of `value` like `Math.random`

**Comment by tabatkins** [comment]
I've changed up the API a bit, dropping the generator in favor of just making it in invocable function that generates a series of values.
